name: CI

on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name : "Mostrar mensaje"
        run: echo "Hola Mundo"
