name: CI

on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    env:
      platform: OpenBMC
      region: Americas
      account: 123456789
    runs-on: ubuntu-latest

    steps:
      - name: "Show Message"
        run: echo "Hola Mundo"

      - name: "Showing Env variables"
        run: |
          echo "Platform: ${{env.platform}}"
          echo "Region: ${{env.region}}"
          echo "Account: ${{env.account}}"
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Python files exist
        id: check_files_py
        run: |
          FILE_COUNT_PY=$(find . -name "*.py" | wc -l)
          if [ "$FILE_COUNT_PY" -eq 0 ]; then
            echo "No Python files found. Skipping flake8."
            echo "py_needed=false" >> $GITHUB_OUTPUT
          else
            echo "py_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check_files_py.outputs.py_needed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: steps.check_files_py.outputs.py_needed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        if: steps.check_files_py.outputs.py_needed == 'true'
        run: flake8 .

  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify C/C++ files exist
        id: check_files
        run: |
          FILE_COUNT=$(find . -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | wc -l)
          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "No C/C++ files found. Skipping Cppcheck."
            echo "cpp_needed=false" >> $GITHUB_OUTPUT_2
          else
            echo "cpp_needed=true" >> $GITHUB_OUTPUT_2
          fi

      - name: Install Cppcheck
        if: steps.check_files.outputs.cppcheck_needed == 'true'
        run: sudo apt-get install cppcheck

      - name: Run Cppcheck
        if: steps.check_files.outputs.cppcheck_needed == 'true'
        run: cppcheck --enable=all --inconclusive --error-exitcode=1 .
