name: CI

on: 

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs: 
  build:
    env:
      platform: OpenBMC
      region: Americas
      account: 123456789
    runs-on: ubuntu-latest

    steps:
      - name: "Show Message"
        run: echo "Hola Mundo"

      - name: "Showing Env variables"
        run: |
          echo "Platform: ${{env.platform}}"
          echo "Region: ${{env.region}}"
          echo "Account: ${{env.account}}"
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .  
